const AUTH_PATHS = {
  BASE: '/auth',
  LOGIN: 'login',
  REGISTER: 'register',
};

const ADMIN_PATHS = {
  BASE: '/admin',
  DASHBOARD: 'dashboard',
};

const USER_PATHS = {
  BASE: '/',
  SEARCH: 'search',
  MUSIC: 'music',
  PODCASTS: 'podcasts',
  PLAYLIST: 'playlist',
  PREMIUM: 'premium',
  GENRE: 'genre',
};

export const _ROUTER_NESTED_PATHS = {
  AUTH: {
    BASE: AUTH_PATHS.BASE,
    LOGIN: AUTH_PATHS.LOGIN,
    REGISTER: AUTH_PATHS.REGISTER,
  },
  ADMIN: {
    BASE: ADMIN_PATHS.BASE,
    DASHBOARD: ADMIN_PATHS.DASHBOARD,
  },
  USER: {
    BASE: USER_PATHS.BASE,
    SEARCH: USER_PATHS.SEARCH,
    MUSIC: USER_PATHS.MUSIC,
    PODCASTS: USER_PATHS.PODCASTS,
    PLAYLIST: USER_PATHS.PLAYLIST,
    PREMIUM: USER_PATHS.PREMIUM,
    GENRE: USER_PATHS.GENRE,
  },
};

const createFullRoutes = () => {
  return {
    HOME: _ROUTER_NESTED_PATHS.USER.BASE,
    SEARCH: `${_ROUTER_NESTED_PATHS.USER.BASE}/${_ROUTER_NESTED_PATHS.USER.SEARCH}`,
    MUSIC: `${_ROUTER_NESTED_PATHS.USER.BASE}/${_ROUTER_NESTED_PATHS.USER.MUSIC}`,
    PODCASTS: `${_ROUTER_NESTED_PATHS.USER.BASE}/${_ROUTER_NESTED_PATHS.USER.PODCASTS}`,
    PLAYLIST: `${_ROUTER_NESTED_PATHS.USER.BASE}/${_ROUTER_NESTED_PATHS.USER.PLAYLIST}`,
    PREMIUM: `${_ROUTER_NESTED_PATHS.USER.BASE}/${_ROUTER_NESTED_PATHS.USER.PREMIUM}`,
    GENRE: `${_ROUTER_NESTED_PATHS.USER.BASE}/${_ROUTER_NESTED_PATHS.USER.GENRE}`,
    // Auth
    LOGIN: `${_ROUTER_NESTED_PATHS.AUTH.BASE}/${_ROUTER_NESTED_PATHS.AUTH.LOGIN}`,
    REGISTER: `${_ROUTER_NESTED_PATHS.AUTH.BASE}/${_ROUTER_NESTED_PATHS.AUTH.REGISTER}`,
  };
};

export const _FULL_ROUTES = createFullRoutes();
